zen-srv
=======

[quote]
A tiny web server that responds to `GET /zen` requests with a new,
inspirational tagline.

Getting the taglines
--------------------
Running the server requires you have a `zens.txt` file in the current
directory. It's just a file containing a different phrase on each line.

[source,bash]
----
./zen-srv fetch --help

Usage of fetch:
  -d="1s": the delay between fetch requests (e.g. 1s, 300ms, 2h45m)
  -n=1: the number of zens to fetch
  -w=4: the number of worker threads to use
  -warn=true: when provided zen-srv will warn about rudeness
----

I recommend using something like this:

[source,bash]
----
./zen-srv fetch -warn=false -n=50 -w=3 -d=1s >> zens.txt
----

Or, it turns out, after running 200 odd queries through `sort` and `uniq`, you
could just use these 14. Bummer.

----
Anything added dilutes everything else.
Approachable is better than simple.
Avoid administrative distraction.
Design for failure.
Encourage flow.
Favor focus over features.
Half measures are as bad as nothing at all.
It's not fully shipped until it's fast.
Keep it logically awesome.
Mind your words, they are important.
Non-blocking is better than blocking.
Practicality beats purity.
Responsive is better than fast.
Speak like a human.
----

Once you've got your `zens.txt` file you can run `zen-srv serve`:

[source,bash]
----
./zen-srv serve -p 8080
----

License
-------
Copyright (c) 2014, Ciaran Downey <code@ciarand.me>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
